// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ticket-server/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: InfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/change_password",
				Handler: ChangePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserToken.AccessSecret),
		rest.WithPrefix("/user"),
	)
}
