// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"ticket-server/app/user/rpc/internal/logic"
	"ticket-server/app/user/rpc/internal/svc"
	"ticket-server/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
