// Code generated by goctl. DO NOT EDIT.
package types

type InfoReq struct {
}

type InfoResp struct {
	Id       string
	Username string
	Balance  float64
}

type RegisterReq struct {
	Username string
	Password string
}

type RegisteraResp struct {
	Ok bool
	Id string
}
